server:
  port: 8080

spring:
  application:
    name: spring-boot-auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database: postgresql
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        format_sql: true
    show_sql: ${DB_SHOW_SQL}
  main:
    web-application-type: servlet

  # Java mail properties
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: ${MAIL_AUTH_ENABLED}
        starttls:
          enabled: ${MAIL_STARTTLS_ENABLED}
        connectiontimeout: ${MAIL_CONNECTION_TIMEOUT}
        timeout: ${MAIL_TIMEOUT}
        writetimeout: ${MAIL_WRITE_TIMEOUT}

application:
  security:
    auth:
      confirmation-url: ${CONFIRMATION_URL}
    jwt:
      # Got from online generate tool
      secret-key: ${JWT_SECRET_KEY}
      # 24 hours expire
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      # 168 hours or 7 days expire
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
