apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spring-boot-auth
data:
  SPRING_APPLICATION_NAME: "spring-boot-auth"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/workshop"
  SPRING_MAIL_HOST: "sandbox.smtp.mailtrap.io"
  SPRING_MAIL_PORT: "2525"
  SPRING_MAIL_USERNAME: "86cee6314b96be"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST: "*"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLED: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: "3000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: "5000"
  APPLICATION_SECURITY_AUTH_CONFIRMATION_URL: "http://spring-boot-auth-service:8080/api/auth/confirm?token=%s"
  APPLICATION_SECURITY_JWT_ACCESS_TOKEN_EXPIRATION: "86400000"
  APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: "604800000"
  POSTGRES_DB: "workshop"
