apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: spring-boot-auth
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # base64 encoded value for 'postgres'
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # base64 encoded value for 'postgres'
  SPRING_MAIL_PASSWORD: ODNkODhjOTczOTIxNGQ= # base64 encoded value for '83d88c9739214d'
  # base64 encoded value for '4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c'
  APPLICATION_SECURITY_JWT_SECRET_KEY: NGJiNmQxZGZiYWZiNjRhNjgxMTM5ZDE1ODZiNmYxMTYwZDE4MTU5YWZkNTdjOGM3OTEzNmQ3NDkwNjMwNDA3Yw==
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded value for 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded value for 'postgres'
